"use client";
import { useMemo, useState } from "react";
import dynamic from "next/dynamic";
import HybridInput from "@/components/ui/HybridInput";
import ResultHero from "@/components/ui/ResultHero";
import InsightCard from "@/components/ui/InsightCard";
import { calcInHandFromCTC } from "@/lib/math";
import { getCtcInsights } from "@/lib/insights";
const CTCFlowChart = dynamic(() => import("./CTCFlowChart"), { ssr: false });
export default function CTCCalculator() {
  const [inputs, setInputs] = useState<{ annualCtc: number; basicPercent: number; hraPercent: number; employerPfContribution: number; gratuity: number; otherAllowancesBonus: number; annualRentPaid: number; cityType: "metro" | "non_metro"; regime: "old" | "new" }>({ annualCtc: 2000000, basicPercent: 40, hraPercent: 20, employerPfContribution: 96000, gratuity: 38462, otherAllowancesBonus: 665538, annualRentPaid: 360000, cityType: "metro", regime: "new" });
  const result = useMemo(() => calcInHandFromCTC(inputs), [inputs]);
  const set = (key: keyof typeof inputs) => (value: number) => setInputs((prev) => ({ ...prev, [key]: value }));
  return <div className="grid grid-cols-1 gap-6 mt-6 lg:grid-cols-[420px_1fr]"><div className="surface-card h-fit space-y-4 p-6 lg:sticky lg:top-6"><HybridInput label="Annual CTC" value={inputs.annualCtc} onChange={set("annualCtc")} min={0} max={100000000} step={100000} prefix="₹" /><HybridInput label="Basic salary" value={inputs.basicPercent} onChange={set("basicPercent")} min={0} max={100} step={1} suffix="% of CTC" /><HybridInput label="HRA" value={inputs.hraPercent} onChange={set("hraPercent")} min={0} max={100} step={1} suffix="% of CTC" /><HybridInput label="Employer PF contribution" value={inputs.employerPfContribution} onChange={set("employerPfContribution")} min={0} max={10000000} step={1000} prefix="₹" /><HybridInput label="Gratuity benefit" value={inputs.gratuity} onChange={set("gratuity")} min={0} max={10000000} step={1000} prefix="₹" /><HybridInput label="Other allowances and bonus" value={inputs.otherAllowancesBonus} onChange={set("otherAllowancesBonus")} min={0} max={100000000} step={10000} prefix="₹" /><HybridInput label="Annual rent paid" value={inputs.annualRentPaid} onChange={set("annualRentPaid")} min={0} max={10000000} step={10000} prefix="₹" /><div className="grid grid-cols-2 gap-2">{(["metro","non_metro"] as const).map((city) => <button key={city} onClick={() => setInputs((p) => ({...p, cityType: city}))} className="rounded-lg border p-2 text-sm">{city === "metro" ? "Metro" : "Non-metro"}</button>)}{(["new","old"] as const).map((regime) => <button key={regime} onClick={() => setInputs((p) => ({...p, regime}))} className="rounded-lg border p-2 text-sm">{regime} regime</button>)}</div></div><div className="space-y-5 min-w-0"><ResultHero label="Monthly in-hand salary" value={result.monthlyInHand} breakdown={[{label:"Annual in-hand",value:result.annualInHand,color:"green"},{label:"Tax deducted",value:result.taxDeducted,color:"red"}]} /><div className="grid grid-cols-1 gap-3 sm:grid-cols-2">{getCtcInsights(result).map((ins, i) => <InsightCard key={i} {...ins} />)}</div><div className="surface-card p-6"><h3 className="mb-4 font-semibold">CTC to in-hand flow</h3><div className="h-[320px]"><CTCFlowChart result={result} /></div></div></div></div>;
}
