import type { Metadata } from "next";
import Link from "next/link";
import { AlertTriangle, Calculator, FileCheck, Scale } from "lucide-react";

export const metadata: Metadata = {
  title: "Terms of Service & Financial Disclaimer",
  description:
    "Terms of service, usage limitations, and financial estimation disclaimers for the FinCalc India financial workspace.",
};

export default function TermsPage() {
  return (
    <main
      id="main-content"
      className="flex-1 max-w-3xl mx-auto px-4 sm:px-6 py-10 sm:py-16 space-y-8"
    >
      <div className="space-y-2 border-b border-border/70 pb-6">
        <h1 className="text-2xl sm:text-3xl font-bold tracking-tight text-foreground">
          Terms of Service & Disclaimer
        </h1>
        <p className="text-xs sm:text-sm text-muted-foreground">
          Effective Date: September 2026 · Guidelines for using FinCalc India
        </p>
      </div>

      <section className="space-y-3">
        <div className="flex items-center gap-2">
          <Calculator className="w-4 h-4 text-primary" />
          <h2 className="text-base font-semibold text-foreground">
            1. Nature of the Service
          </h2>
        </div>
        <p className="text-xs sm:text-sm text-muted-foreground leading-relaxed">
          FinCalc India provides a specialized suite of mathematical, financial, and tax modeling
          calculators designed for individuals, chartered accountants, financial advisors, and
          corporates in India.
        </p>
        <p className="text-xs sm:text-sm text-muted-foreground leading-relaxed">
          Access to the calculators requires an authenticated account. By signing in, you are
          granted a personal, revocable license to utilize the workspace for planning, simulation,
          and estimation purposes.
        </p>
      </section>

      <section className="space-y-3">
        <div className="flex items-center gap-2">
          <AlertTriangle className="w-4 h-4 text-amber-500" />
          <h2 className="text-base font-semibold text-foreground">
            2. Educational & Estimation Disclaimer
          </h2>
        </div>
        <p className="text-xs sm:text-sm text-muted-foreground leading-relaxed">
          All financial calculations, projections, amortizations, and evaluations generated by FinCalc
          India are estimates intended solely for educational, informational, and personal planning purposes.
        </p>
        <ul className="list-disc list-inside text-xs sm:text-sm text-muted-foreground space-y-1.5 pl-2">
          <li>
            <strong>Not Investment Advice:</strong> Return projections (such as SIP compounding,
            FIRE simulations, and DCF enterprise valuations) are mathematical models based on user-supplied
            parameters and constant rate assumptions. Actual market performance fluctuates and is subject
            to risk.
          </li>
          <li>
            <strong>Not Tax or Legal Advice:</strong> Tax calculations incorporate codified statutory
            rules (including the Income-tax Act, 2025 for Tax Year 2026–27). However, individual tax liabilities
            depend on comprehensive personal circumstances, specific exemptions, and evolving CBDT notifications.
          </li>
        </ul>
      </section>

      <section className="space-y-3">
        <div className="flex items-center gap-2">
          <Scale className="w-4 h-4 text-primary" />
          <h2 className="text-base font-semibold text-foreground">
            3. Statutory Assumptions & Updates
          </h2>
        </div>
        <p className="text-xs sm:text-sm text-muted-foreground leading-relaxed">
          We strive to maintain high accuracy and reflect current Indian regulatory statutes,
          including PFRDA exit guidelines, RBI retail lending norms, SEBI margin mandates, and
          Union Budget statutory tax brackets. Each calculator provides an accessible Assumptions Drawer
          outlining the mathematical formulas and legal sections applied.
        </p>
        <p className="text-xs sm:text-sm text-muted-foreground leading-relaxed">
          Users should independently verify figures with certified financial planners, tax consultants,
          or legal professionals before making binding investment, borrowing, or filing decisions.
        </p>
      </section>

      <section className="space-y-3">
        <div className="flex items-center gap-2">
          <FileCheck className="w-4 h-4 text-primary" />
          <h2 className="text-base font-semibold text-foreground">
            4. User Responsibility & Account Security
          </h2>
        </div>
        <p className="text-xs sm:text-sm text-muted-foreground leading-relaxed">
          You are responsible for maintaining the security of your Google account credentials used
          to sign in to FinCalc India. You agree not to abuse, reverse-engineer, or attempt unauthorized
          access to any private calculations or underlying application infrastructure.
        </p>
      </section>

      <div className="pt-6 border-t border-border/70 flex items-center justify-between">
        <Link
          href="/login"
          className="text-xs font-semibold text-primary hover:underline"
        >
          ← Return to Sign In
        </Link>
        <Link
          href="/privacy"
          className="text-xs text-muted-foreground hover:text-foreground transition-colors"
        >
          View Privacy Policy →
        </Link>
      </div>
    </main>
  );
}
